CI test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,12 +14,14 @@ check_version:
   before_script:
     - apk add --no-cache bash
   script:
-    - bash -c '
+    - |
+      bash -eo pipefail <<'EOF'
       if [[ ! "$CI_COMMIT_TAG" =~ ^([0-9]+(\.[0-9]+){1,3})(-(stable|alpha|beta|nightly|dev))?$ ]]; then
-      echo "❌ Tag format invalid!"
-      exit 1
+        echo "❌ Tag format invalid!"
+        exit 1
       fi
       echo "✅ Tag format OK"
+      EOF
 
 
 .build:
